### ISSUE TITLE
[ENHANCEMENT] Allow to configure line size of drawn polygons of a given layer.

### ISSUE THREAD

**Issue by sebastienbinda** [MizarWeb/MizarWeb.github.io#1]
It would be very usefull to be able to configure line size (in pixels for exemple) when drawing polygons on a given layer.

**Comment by J-Christophe** [comment]
Hello Sébastien,

After checking, it is already possible by the use of **strokeWidth** attribute in **style**. You can define a style in three ways : 

- in the layer definition (see the **example 1** as below)
- by updating the layer definition (see the **example 2** as below)
- in the **properties** of the GeoJson by defining a **style** attribute

When the style is not defined, it is automatically [created](https://github.com/MizarWeb/Mizar/blob/5250188e53860756a7e88cf86d90fca0f15e18d0/src/Layer/AbstractLayer.js#L212-L247) and the color of the line is random. So I think, you should use the second way in order to keep the color as random

In addition, you can have a look at the different attributes on a [style](https://github.com/MizarWeb/Mizar/blob/master/src/Renderer/FeatureStyle.js
) 


**Example 1**
`// create an empty layer, by default visible`
`mizar.addLayer({`
`    type: Mizar.LAYER.GeoJSON,`
`    visible: true,`
`    style: {`
`       strokeWidth:5	    `
`    }	    `
`}, function (layerID) {`
`[...]`
`});`
`


**Example 2**
`// create an empty layer, by default visible`
`mizar.addLayer({`
`    type: Mizar.LAYER.GeoJSON,`
`    visible: true    `
`}, function (layerID) {`
`    // get the empty layer`
`    var layer = mizar.getLayerByID(layerID);`
`    var style = layer.getStyle();`
`    style.strokeWidth = 5;`
` [...]`
`});`

**Comment by sebastienbinda** [comment]
Thanks, the style.strokeWidth with the "Exemple 1" did the job for me. Nevertheless, it seems that the property is applied for all other layers when i do 
```js
this.mizar.addLayer({
      type: Mizar.LAYER.GeoJSON,
      name: 'geojson',
      visible: true,
      background: false,
      style: {
        color: 'red',
        stokeWidth: 10,
      },
    }, (geojsonLayerId) => {
      this.geojsonLayerId = geojsonLayerId
    })
```

The style is applied to all layers after featureCollection is added to the layer.
